administrator/urls.py
from django.urls import path, include
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.index, name='index'),
    path('dataset/', views.dataset, name='dataset'),
    path('tentang/', views.tentang, name='tentang'),
    path('EDA/', views.EDA, name='EDA'),
    path('encode/', views.encode, name='encode'),
    path('split_data_chi2/', views.SplitData, name='split_data_chi2'),
    #path('klasifikasi/', views.klasifikasi, name='klasifikasi'),
    path('Catboost/', views.Catboost, name='Catboost'),
    path('Catboost_Chi2/', views.Catboost_Chi2, name='Catboost_Chi2'),
    path('hasil_catboost_chi2/', views.hasil_catboost_chi2, name='hasil_catboost_chi2'),
    #path('hasilsvmrbf/', views.hasilsvmrbf, name='hasilsvmrbf'),
    #path('SVMRBFIG/', views.SVMRBFIG, name='SVMRBFIG'),
    path('live_test/', views.live_test, name="live_test"),
    path('live_test_hasil/', views.live_test_hasil, name="live_test_hasil"),
    path('live_test2/', views.live_test2, name="live_test2"),
    path('live_test_hasil2/', views.live_test_hasil2, name="live_test_hasil2")
]

xdata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
        path('login/', views.custom_login, name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('', views.custom_login, name='index'),
        path('administrator/', include('administrator.urls', namespace='administrator')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.

administrator/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import decorator_from_middleware
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.contrib import messages
import random
from operator import itemgetter
import zipfile
import os
from shutil import copyfile
from matplotlib import pyplot

#Plotly
import plotly.express as px
import plotly.graph_objs as go
import plotly.figure_factory as ff
from plotly import tools
from plotly.offline import plot


#End Plotly

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from time import time

#Sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.metrics import accuracy_score
from sklearn import model_selection
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold
from sklearn import naive_bayes
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
#from genetic_selection import GeneticSelectionCV
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

import time
import numpy as np

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from catboost import CatBoostClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import RepeatedStratifiedKFold
from matplotlib import pyplot

import pickle


# Create your views here.
default_test_size = 0.2
default_ranking = 12

Features = None
Target = None

X_train = X_test = y_train = y_test = X_train_fs = X_test_fs =  None 



@login_required(login_url=settings.LOGIN_URL)
def index(request):
    return render(request, 'administrator/dashboard.html')

@login_required(login_url=settings.LOGIN_URL)
def tentang(request):
    return render(request, 'administrator/tentang.html')

#@login_required(login_url=settings.LOGIN_URL)
#def SVM(request):
#    return render(request, 'administrator/SVM.html')

# @login_required(login_url=settings.LOGIN_URL)
# def Catboost_Chi2(request):
#     return render(request, 'administrator/catboosts_chi2.html')

#@login_required(login_url=settings.LOGIN_URL)
#def SVMRBFIG(request):
#    return render(request, 'administrator/SVMRBFIG.html')


##Main Module

@login_required(login_url=settings.LOGIN_URL)
def dataset(request):
    if request.method == 'POST':
        file = request.FILES['data']
        if default_storage.exists('dataset.csv'):
            default_storage.delete('dataset.csv')
        file_name = default_storage.save('dataset.csv', file)

        dataset = []
        data = pd.read_csv(default_storage.path('dataset.csv'))
        data.rename(columns={   
                            'gender':'Gender',
                            'NationalITy':'Nationality',
                            'VisITedResources':'VisitedResources',
                            'ParentschoolSatisfaction':'ParentSchoolSatisfaction',
                            'raisedhands':'raisedHands'
                            }, inplace=True) 
        
        data['Nationality'].replace({
                                    'KW':'Kuwait',
                                    'venzuela':'Venezuela',
                                    'Lybia':'Libya',
                                    'lebanon':'Lebanon',
                                    'Tunis':'Tunisia'
                                    },inplace=True)
        
        data['PlaceofBirth'].replace({
                                    'venzuela':'Venezuela',
                                    'Lybia':'Libya',
                                    'lebanon':'Lebanon',
                                    'KuwaIT':'Kuwait',
                                    'Tunis':'Tunisia'
                                    },inplace=True)
        data.to_csv("media/dataset.csv", index=False)
        
        for x in range(len(data['Gender'])):
            temp = []
            temp.append(data['Gender'][x])
            temp.append(data['Nationality'][x])
            temp.append(data['PlaceofBirth'][x])
            temp.append(data['StageID'][x])
            temp.append(data['GradeID'][x])
            temp.append(data['SectionID'][x])
            temp.append(data['Topic'][x])
            temp.append(data['Semester'][x])
            temp.append(data['Relation'][x])
            temp.append(data['raisedHands'][x])
            temp.append(data['VisitedResources'][x])
            temp.append(data['AnnouncementsView'][x])
            temp.append(data['Discussion'][x])
            temp.append(data['ParentAnsweringSurvey'][x])
            temp.append(data['ParentSchoolSatisfaction'][x])
            temp.append(data['StudentAbsenceDays'][x])
            temp.append(data['Class'][x])
            
            # print(data['sentiment'][x])
            dataset.append(temp)
        # path = default_storage.save('dataset.csv', ContentFile(file.read()))
        messages.success(request,'Dataset berhasil diupload!')

        return render(request, 'administrator/dataset.html',{'dataset': dataset})
    else:
        if default_storage.exists('dataset.csv'):
            dataset = []
            data = pd.read_csv(default_storage.path('dataset.csv'))
            
            data.rename(columns={   
                            'gender':'Gender',
                            'NationalITy':'Nationality',
                            'VisITedResources':'VisitedResources',
                            'ParentschoolSatisfaction':'ParentSchoolSatisfaction',
                            'raisedhands':'raisedHands'
                            }, inplace=True) 
        
        data['Nationality'].replace({
                                    'KW':'Kuwait',
                                    'venzuela':'Venezuela',
                                    'Lybia':'Libya',
                                    'lebanon':'Lebanon',
                                    'Tunis':'Tunisia'
                                    },inplace=True)
        
        data['PlaceofBirth'].replace({
                                    'venzuela':'Venezuela',
                                    'Lybia':'Libya',
                                    'lebanon':'Lebanon',
                                    'KuwaIT':'Kuwait',
                                    'Tunis':'Tunisia'
                                    },inplace=True)
        
        data.to_csv("media/dataset.csv", index=False)    
        print(data['Class'])
        for x in range(len(data['Gender'])):
            temp = []
            temp.append(data['Gender'][x])
            temp.append(data['Nationality'][x])
            temp.append(data['PlaceofBirth'][x])
            temp.append(data['StageID'][x])
            temp.append(data['GradeID'][x])
            temp.append(data['SectionID'][x])
            temp.append(data['Topic'][x])
            temp.append(data['Semester'][x])
            temp.append(data['Relation'][x])
            temp.append(data['raisedHands'][x])
            temp.append(data['VisitedResources'][x])
            temp.append(data['AnnouncementsView'][x])
            temp.append(data['Discussion'][x])
            temp.append(data['ParentAnsweringSurvey'][x])
            temp.append(data['ParentSchoolSatisfaction'][x])
            temp.append(data['StudentAbsenceDays'][x])
            temp.append(data['Class'][x])
            
            # print(data['sentiment'][x])
            dataset.append(temp)

            # with open(default_storage.path('dataset.csv'), 'r') as data:
            #     reader = csv.reader(data)
            #     dataset = []
            #     for row in reader:
            #         dataset.append(row)
            # print(dataset)

        else:
            dataset = []
        # nama=[]
        # jumlah=[]
        # dataset=[]
        # if default_storage.exists('dataset'):
        #     for name in os.listdir(os.path.join(settings.BASE_DIR, 'media/dataset')):
        #         dataset.append([str(name),str(len(os.listdir(os.path.join(settings.BASE_DIR, 'media/dataset/'+name))))])
        # # print(dataset)
        
        return render(request, 'administrator/dataset.html',{'dataset': dataset})

@login_required(login_url=settings.LOGIN_URL)
def EDA(request):
    
    if default_storage.exists('dataset.csv'):
        data = pd.read_csv(default_storage.path('dataset.csv'))
        
        #Graf Kelas
        kelas_data = px.bar(
                            data, x = data['Class'].unique(), y = data['Class'].value_counts(), 
                            color = data['Class'].unique(), 
                            title="Graf Kelas",
                            labels={
                                "x": "Kelas",
                                "y": "Jumlah"
                                }
                            )
        plot_kelas = plot(kelas_data, output_type='div')
        
        #Graf Gender
        gender_data = px.bar(
                            data, x = data['Gender'].unique(), y = data['Gender'].value_counts(), 
                            color = data['Gender'].unique(), 
                            title="Graf Gender",
                            labels={
                                "x": "Gender",
                                "y": "Jumlah"
                                }
                            )
        plot_gender = plot(gender_data, output_type='div')
        
        #Graf StageID
        stageid_data = px.bar(
                            data, x = data['StageID'].unique(), y = data['StageID'].value_counts(), 
                            color = data['StageID'].unique(), 

templates/administrator/EDA.html
{% extends "layouts/administrator.html" %}
{% load static %}

{% block EDA %}
active-sub
{% endblock %}

{% block title %}
Hasil | Klasifikasi Analisis Sentimen Movie Review
{% endblock %}

{% block css %}
<!--DataTables [ OPTIONAL ]-->
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
<!--Animate.css [ OPTIONAL ]-->
<link href="{% static 'plugins/animate-css/animate.min.css' %}" rel="stylesheet">

  <link href="{% static "plugins/dropify/css/dropify.css" %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
<div id="content-container">
    <div id="page-head">

<div class="pad-all text-center">
<h3>Hasil Text Pre-processing</h3>
<p>TOKENIZE, FILTER TOKEN, FILTER STOPWORDS, & STEMMING</p>
</div>
        </div>


    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">
        <div class="panel">
              <div class="panel-heading">
                  <h3 class="panel-title">Result Tokenize & Filter Token</h3>
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_kelas }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_stageid }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_semester }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_topic }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_nationality }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_class }}
                {% endautoescape %}
                  
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_relation }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_absen }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_parentSurvey }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_topic }}
                {% endautoescape %}
                
              </div>

              <div class="panel-body">
                {% autoescape off %}
                {{ plot_div_gender_to_nationality }}
                {% endautoescape %}
                
              </div>

        </div>

  <div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Process</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <a  class="btn btn-lg btn-primary" href="{% url 'administrator:encode' %}">Proses Encoding Data</a>
            </div>
</div>

    <!--===================================================-->
    <!--End page content-->

</div>

<div id="demo-lg-modal" class="modal fade" tabindex="-1">
      <div class="modal-dialog modal-lg animated bounceIn">
          <div class="modal-content">
            <form class="formValidate2" id="formValidate2" name="form_tambah" method="post" action="{% url 'administrator:dataset' %}" enctype="multipart/form-data">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                  <h4 class="modal-title" id="myLargeModalLabel">Import Dataset</h4>
              </div>
              <div class="modal-body">

                  {% csrf_token %}
                <div class="row section">
            <div class="col-sm-12">
                <p>Upload Dataset (Maximum file upload size 10MB).</p>
                <input type="file" name="data" class="dropify" data-show-remove="false" data-allowed-file-extensions="csv" data-max-file-size="10M" required />
                    </div>
            </div>


              </div>

              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>

              </form>
          </div>
      </div>
  </div>
{% endblock %}

{% block js %}

 <!--DataTables [ OPTIONAL ]-->
 <script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>


 <!--DataTables Sample [ SAMPLE ]-->
<script type="text/javascript">

  // Tables-DataTables.js
  // ====================================================================
  // This file should not be included in your project.
  // This is just a sample how to initialize plugins or components.
  //
  // - ThemeOn.net -



  $(document).on('nifty.ready', function() {


      // DATA TABLES
      // =================================================================
      // Require Data Tables
      // -----------------------------------------------------------------
      // http://www.datatables.net/
      // =================================================================

      $.fn.DataTable.ext.pager.numbers_length = 5;


      // Basic Data Tables with responsive plugin
      // -----------------------------------------------------------------
      $('#demo-dt-basic').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic2').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic3').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic4').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );

      $('#demo-dt-basic5').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic6').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );





      // Row selection (single row)
      // -----------------------------------------------------------------
      var rowSelection = $('#demo-dt-selection').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      });

      $('#demo-dt-selection').on( 'click', 'tr', function () {
          if ( $(this).hasClass('selected') ) {
              $(this).removeClass('selected');
          }
          else {
              rowSelection.$('tr.selected').removeClass('selected');
              $(this).addClass('selected');
          }
      } );






      // Row selection and deletion (multiple rows)
      // -----------------------------------------------------------------
      var rowDeletion = $('#demo-dt-delete').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          },
          "dom": '<"toolbar">frtip'
      });
      $('#demo-custom-toolbar').appendTo($("div.toolbar"));

      $('#demo-dt-delete tbody').on( 'click', 'tr', function () {
          $(this).toggleClass('selected');
      } );

      $('#demo-dt-delete-btn').click( function () {
          rowDeletion.rows('.selected').remove().draw( false );
      } );






      // Add Row
      // -----------------------------------------------------------------
      var t = $('#demo-dt-addrow').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          },
          "dom": '<"newtoolbar">frtip'
      });
      $('#demo-custom-toolbar2').appendTo($("div.newtoolbar"));

      var randomInt = function(min,max){
          return Math.floor(Math.random()*(max-min+1)+min);
      }
      $('#demo-dt-addrow-btn').on( 'click', function () {
          t.row.add( [
              'Adam Doe',
              'New Row',
              'New Row',
              randomInt(1,100),
              '2015/10/15',
              '$' + randomInt(1,100) +',000'
          ] ).draw();
      } );


  });

</script>
 <!--Bootbox Modals [ OPTIONAL ]-->
<script src="{% static 'plugins/bootbox/bootbox.min.js' %}"></script>

<script type="text/javascript" src="{% static "plugins/dropify/js/dropify.js" %}"></script>

{% endblock %}

templates/administrator/dataset.html
{% extends "layouts/administrator.html" %}
{% load static %}

{% block dataset %}
active-sub
{% endblock %}

{% block title %}
Sentimen Analisis | Klasifikasi Analisis Sentimen Movie Review
{% endblock %}

{% block css %}
<!--DataTables [ OPTIONAL ]-->
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
<!--Animate.css [ OPTIONAL ]-->
<link href="{% static 'plugins/animate-css/animate.min.css' %}" rel="stylesheet">

  <link href="{% static "plugins/dropify/css/dropify.css" %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
<div id="content-container">
    <div id="page-head">

<div class="pad-all text-center">
<h3>Dataset Movie Review</h3>
<p>IMPORT DATASET</p>
</div>
        </div>


    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">
      <div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">Dataset </h3>
					    </div>

					    <div class="panel-body">

					        <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
					            <thead>
					                <tr>

					                    <th>Gender</th>
					                    <th>Nationality</th>
                                        <th>Tempat Lahir</th>
					                    <th>Jenjang Sekolah</th>
                                        <th>GradeID</th>
					                    <th>SectionID</th>
                                        <th>Topik</th>
					                    <th>Semester</th>
                                        <th>Relasi Ortu</th>
					                    <th>Mengangkat Tangan</th>
                                        <th>Melihat Materi</th>
                                        <th>Melihat Pengumuman</th>
					                    <th>Diskusi</th>
                                        <th>Orang Tua Menjawab Survey</th>
					                    <th>Kepuasan Orang Tua kepada Sekolah</th>
                                        <th>Siswa Absen</th>
					                    <th>Hasil</th>
                                        
					                </tr>
					            </thead>
					            <tbody>
                        {% for x in dataset %}
                          <tr>
                              <td>{{x.0}}</td>
                              <td>{{x.1}}</td>
                              <td>{{x.2}}</td>
                              <td>{{x.3}}</td>
                              <td>{{x.4}}</td>
                              <td>{{x.5}}</td>
                              <td>{{x.6}}</td>
                              <td>{{x.7}}</td>
                              <td>{{x.8}}</td>
                              <td>{{x.9}}</td>
                              <td>{{x.10}}</td>
                              <td>{{x.11}}</td>
                              <td>{{x.12}}</td>
                              <td>{{x.13}}</td>
                              <td>{{x.14}}</td>
                              <td>{{x.15}}</td>
                              <td>{{x.16}}</td>
                          </tr>
                        {% endfor %}
					            </tbody>
					        </table>
					    </div>
					</div>


          <div class="panel">
    					    <div class="panel-heading">
    					        <h3 class="panel-title">Import Dataset</h3>
    					    </div>
    					    <div class="panel-body demo-nifty-btn">
                    <button data-target="#demo-lg-modal" data-toggle="modal" class="btn btn-lg btn-primary">Import</button>
                    </div>
  </div>


  <div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Process</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <a  class="btn btn-lg btn-primary" href="{% url 'administrator:EDA' %}">Explanatory Data Analisys</a>
            </div>
</div>
    <!--===================================================-->
    <!--End page content-->

</div>

<div id="demo-lg-modal" class="modal fade" tabindex="-1">
      <div class="modal-dialog modal-lg animated bounceIn">
          <div class="modal-content">
            <form class="formValidate2" id="formValidate2" name="form_tambah" method="post" action="{% url 'administrator:dataset' %}" enctype="multipart/form-data">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                  <h4 class="modal-title" id="myLargeModalLabel">Import Dataset</h4>
              </div>
              <div class="modal-body">

                  {% csrf_token %}
                <div class="row section">
            <div class="col-sm-12">
                <p>Upload Dataset (Maximum file upload size 10MB).</p>
                <input type="file" name="data" class="dropify" data-show-remove="false" data-allowed-file-extensions="csv" data-max-file-size="10M" required />
                    </div>
            </div>


              </div>

              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>

              </form>
          </div>
      </div>
  </div>
{% endblock %}

{% block js %}

 <!--DataTables [ OPTIONAL ]-->
 <script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>


 <!--DataTables Sample [ SAMPLE ]-->
 <script src="{% static 'js/demo/tables-datatables.js' %}"></script>
 <!--Bootbox Modals [ OPTIONAL ]-->
<script src="{% static 'plugins/bootbox/bootbox.min.js' %}"></script>

<script type="text/javascript" src="{% static "plugins/dropify/js/dropify.js" %}"></script>


 <script>
$(document).ready(function(){
    $('.dropify').dropify();

      // Translated
      $('.dropify-fr').dropify({
          messages: {
              default: 'Glissez-déposez un fichier ici ou cliquez',
              replace: 'Glissez-déposez un fichier ou cliquez pour remplacer',
              remove:  'Supprimer',
              error:   'Désolé, le fichier trop volumineux'
          }
      });

      // Used events
      var drEvent = $('.dropify-event').dropify();
      drEvent.on('dropify.beforeClear', function(event, element){
          return confirm("Do you really want to delete \"" + element.filename + "\" ?");
      });

      drEvent.on('dropify.afterClear', function(event, element){
          alert('File deleted');
      });
        });
 </script>
{% endblock %}